### PR TITLE
Level up the .gitignore

### PR DESCRIPTION
**Pull request by stephenyeargin**
This steals from https://github.com/github/gitignore/blob/master/Rails.gitignore

### CODE REVIEW

**Comment by stephenyeargin** [comment]
This merges into `rewrite` since that's the main development branch at the moment.

**Review by jameswhite — COMMENTED** [review]
👍

**Comment by stephenyeargin** [comment]
I don't have merge access, so it's all you.

**Comment by jameswhite** [comment]
Collaborator invite sent, @stephenyeargin

**Pull request merged**
